import { UserProvider } from "./context/UserContext";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <UserProvider>
        {children} {/*Wrap everything in the UserProvider context*/}
      </UserProvider>
      </body>
    </html>
  );
}
